#include "BatteryBSP.h"

// Import the ADC variable generated by STM32CubeMX in main.c
extern ADC_HandleTypeDef hadc1; 

uint16_t BSP_GetBatteryVoltage(void)
{
    uint32_t adc_value = 0;
    uint16_t voltage_mv = 0;

    // 1. Start the ADC reading
    HAL_ADC_Start(&hadc1);
    
    // 2. Wait for the conversion to complete (with a timeout of 10ms)
    if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
    {
        // 3. Get the raw ADC value (a number between 0 and 4095)
        adc_value = HAL_ADC_GetValue(&hadc1);
        
        // 4. Convert the raw value to millivolts.
        // Multiply by 3300mV (maximum of the board) and divide by 4095
        voltage_mv = (uint16_t)((adc_value * 3300) / 4095);
    }

    // 5. Return the converted voltage
    return voltage_mv;
}